blog/urls.py
from django.conf.urls import url, include

from .views import *

restaurant/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from homepage.views import *
from django.contrib.sitemaps.views import sitemap
from site_map.views import *

sitemaps = {
    'static_hm': StaticViewSitemap,
    'blog': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', view=Homepage.as_view(), name='homepage'),
    url(r'^about/$', RedirectView.as_view(url='/', permanent=False), name='about'),
    url(r'^reservation/$', ReservationPage.as_view(), name='reservation'),
    url(r'^menu/$', MenuPage.as_view(), name='menu'),
    url(r'^menu/(?P<slug>[-\w]+)/$', MenuPageDetails.as_view(), name='menu_detail'),
    url(r'^blog/$', BlogPageGre.as_view(), name='blog'),
    url(r'^contact/$', ContactPage.as_view(), name='contact'),
    url(r'^blog/(?P<slug>[-\w]+)/$', BlogDetail.as_view(), name='blog_detail'),
    url(r'^set-english/$', view=switch_to_English_link, name='eng_cookie'),
    url(r'^set-greek/$', view=switch_to_Greek_link, name='gre_cookie'),

    url(r'^en/$', HomepageEng.as_view(), name='homepage_eng'),
    url(r'^en/about/$', RedirectView.as_view(url='/', permanent=False), name='about_eng'),
    url(r'^en/reservation/$', ReservationPageEng.as_view(), name='reservation_eng'),
    url(r'^en/menu/$', MenuPageEng.as_view(), name='menu_eng'),
    url(r'^en/menu/(?P<slug>[-\w]+)/$', MenuPageDetailsEng.as_view(), name='menu_detail_eng'),
    url(r'^en/blog/$', BlogPageEng.as_view(), name='blog_eng'),
    url(r'^en/contact/$', ContactPageEng.as_view(), name='contact_eng'),
    url(r'^en/blog/(?P<slug>[-\w]+)/$', BlogDetailEng.as_view(), name='blog_detail_eng'),
    url(r'^set-english/$', view=switch_to_English_link, name='eng_cookie'),
    url(r'^set-greek/$', view=switch_to_Greek_link, name='gre_cookie'),
    url(r'^sitemap\.xml', sitemap, {'sitemaps': sitemaps}),
    url(r'^robots\.txt$', include('robots.urls')),

    #url(r'^.*$', RedirectView.as_view(url='/', permanent=False), name='index'),
    url(r'^cache-clear/', view=cache_clear, name='cache_clear'),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
import datetime
from django.utils.safestring import mark_safe
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType

from mptt.models import MPTTModel, TreeForeignKey
from tinymce.models import HTMLField
# Create your models here.

MAX_POST_SIZE_FILE = 0.5*1024*1024


def validate_image(value):
    if value.file.size > MAX_POST_SIZE_FILE:
        return ValidationError('Το αρχείο είναι μεγαλύτερο από 0,5mb.')
    return value


def upload_file(instance, filename):
    return 'blog/%s/%s'%(instance.title, filename)


def upload_file_gallery(instance, filename):
    return 'gallery/%s/%s'%(instance.title, filename)


class PostTags(models.Model):
    title = models.CharField(max_length=100,)
    title_eng = models.CharField(max_length=100,default='English')

    class Meta:
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.title


class PostCategory(MPTTModel):
    title = models.CharField(max_length=100, unique=True, )
    slug = models.SlugField(blank=True, null=True, allow_unicode=True)
    content = models.CharField(max_length=150, null=True, blank=True)
    title_eng = models.CharField(max_length=100, default='English')
    parent = TreeForeignKey('self', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Κατηγορία blog'

    def __str__(self):
        return self.title

    def posts_count(self):
        return Post.objects.filter(category=self).count()


class PostManager(models.Manager):
    def active(self):
        return super(PostManager, self).filter(active=True)

    def return_last_five(self):
        return super(PostManager, self).all()[0:5]

    def active_announcements(self):
        return super(PostManager, self).filter(active=True, announcement=True)

    def active_and_english_post(self):
        return super(PostManager, self).filter(active = True, active_english=True)

    def active_and_english_announcement(self):
        return super(PostManager, self).filter(active = True, active_english=True, announcement=True)

    def show_homepage(self):
        return super(PostManager, self).filter(active=True, show_homepage=True)

    def show_homepage_eng(self):
        return super(PostManager, self).filter(active=True, show_homepage=True, active_english=True)


class Post(models.Model):
    show_homepage = models.BooleanField(default=True, verbose_name='Εμφάνιση στην αρχική σελίδα')
    active = models.BooleanField(default=True)
    active_english = models.BooleanField(default=False, verbose_name='Εμφάνιση στην Αγγλική Version')
    title = models.CharField(max_length=100, verbose_name='Τίτλος')
    image = models.ImageField(upload_to=upload_file, validators=[validate_image, ], help_text='Το μέγεθος πρέπει να είναι μέχρι 0,5 mb')
    content = HTMLField(verbose_name='Κείμενο', null=True)
    publish = models.DateField(auto_now=True, auto_now_add=False, verbose_name='Ημερομηνία Δημιουργίας')
    updated = models.DateTimeField(default=datetime.datetime.now(), verbose_name='Ημερομηνία Event/Παρουσίασης')
    slug = models.SlugField(unique=True,null=True, blank=True, allow_unicode=True, verbose_name='Slug - Dont bother with that ')
    category = models.ForeignKey(PostCategory, null=True, verbose_name='Κατηγορία')
    tags = models.ManyToManyField(PostTags, null=True, blank=True)
    announcement = models.BooleanField(default=False, verbose_name='Ανακοίνωση')
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')
    title_eng = models.CharField(max_length=100, verbose_name='Title', default='English tile')
    content_eng = HTMLField(verbose_name='Short description or Intro', default='English text', null=True,)
    # seo
    seo = models.CharField(max_length=100, blank=True, verbose_name='Keywords')
    meta_description = models.CharField(max_length=100, blank=True, verbose_name='Description')
    keywords_eng = models.CharField(max_length=100, blank=True, verbose_name='English Keywords')
    meta_description_eng = models.CharField(max_length=100, blank=True, verbose_name='English Description')

    my_query = PostManager()
    objects = models.Manager()

    class Meta:
        verbose_name_plural = 'Blog'
        ordering = ['-updated']

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img width="150px" height="150px" src="https://laggis.s3.amazonaws.com/media/%s" />' %(self.image))

    def image_tag_tiny(self):
        return mark_safe('<img width="50px" height="50px" src="https://laggis.s3.amazonaws.com/media/%s" />' %(self.image))
    image_tag_tiny.short_description = 'Image'

    def absolute_url(self):
        return reverse("blog_detail", kwargs={"slug": self.slug})

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    def get_absolute_url(self):
        return reverse('blog_detail', kwargs={'slug':self.slug})


class Gallery(models.Model):
    image = models.ImageField(upload_to=upload_file_gallery, validators=[validate_image,])
    post_related = models.ForeignKey(Post)

    def __str__(self):
        return '%s %s' % (self.post_related.title, self.id)

    def image_tag_tiny(self):
        return mark_safe(
            '<img width="50px" height="50px" src="https://laggis.s3.amazonaws.com/media/%s" />' % (self.image))
    image_tag_tiny.short_description = 'Image'

contact/models.py
from django.db import models
import datetime
# Create your models here.


class ContactInfo(models.Model):
    # the real contact model
    date = models.DateTimeField(default=datetime.datetime.now(), verbose_name='Ημερομηνία Δημιουργίας')
    name = models.CharField(max_length=255, verbose_name='Ονοματεπώνυμο')
    phone = models.CharField(max_length=10, blank=True, null=True, verbose_name='Τηλέφωνο')
    email = models.EmailField(blank=True, null=True,)
    message = models.TextField(verbose_name='Μήνυμα', blank=True, null=True)
    is_readed = models.BooleanField(default=False, verbose_name='Το έχεις δει;')

    class Meta:
        verbose_name_plural = '2. Επικοινωνία'

    def __str__(self):
        return self.name


class ContactInfoPage(models.Model):
    open_time = models.CharField(default='Ωρες Λειτουργίας', max_length=160, verbose_name='Τίτλος, Ωρες Λειτουργίας στα Ελληνικά')
    address = models.CharField(default='Διεύθυνση', max_length=160, verbose_name='Τίτλος Διεύθυνση στα Ελληνικά')
    address_text = models.TextField(default='', verbose_name='Κείμενο Διεύθυνση στα Ελληνικά')
    support = models.CharField(default='Support', verbose_name='Τίτλος Ωρες support στα Ελληνικά', max_length=160)
    support_text = models.TextField(default='', verbose_name='Κείμενο support στα Ελληνικά')
    open_time_eng = models.CharField(default='Ωρες Λειτουργίας', max_length=160, verbose_name='Τίτλος, Ωρες Λειτουργίας στα Αγγλικά')
    address_eng = models.CharField(default='Διεύθυνση', max_length=160, verbose_name='Τίτλος Διεύθυνση στα Αγγλικά')
    address_text_eng = models.TextField(default='', verbose_name='Κείμενο Διεύθυνση στα Αγγλικά')
    support_eng = models.CharField(default='Support', verbose_name='Τίτλος Ωρες support στα Αγγλικά', max_length=160)
    support_text_eng = models.TextField(default='', verbose_name='Κείμενο support στα Αγγλικά')

    class Meta:
        verbose_name_plural = '4. Διαχείριση Πληροφορίες Contact Page'

    def __str__(self):
        return self.open_time


class Contact(models.Model):
    #that used for reservations
    date = models.DateTimeField(default=datetime.datetime.now(), verbose_name='Ημερομηνία Δημιουργίας')
    name = models.CharField(max_length=255, verbose_name='Ονοματεπώνυμο')
    phone = models.CharField(blank=True, null=True, verbose_name='Τηλέφωνο', max_length=10)
    email = models.EmailField(blank=True, null=True,)
    people = models.IntegerField(default=2, verbose_name="'Ατομα")
    message = models.TextField(verbose_name='Μήνυμα', blank=True, null=True)
    resever_date = models.CharField(max_length=50, default='05/02/17', verbose_name='Ημερομηνία Κράτησης')
    time = models.CharField(verbose_name="'Ωρα Κράτησης", max_length=15)
    is_readed = models.BooleanField(default=False, verbose_name='Το έχεις δει;')

    class Meta:
        verbose_name_plural = '1. Κρατήσεις'

    def __str__(self):
        return self.name


class ReservationInfo(models.Model):
    active = models.BooleanField(default=True)
    left_title = models.CharField(default='Αριστερός τίτλος στα Ελληνικά', max_length=160, verbose_name='Τίτλος στα Ελληνικά')
    right_title = models.CharField(default='Δεξιός τίτλος στα Ελληνικά', max_length=160, verbose_name='Τίτλος στα Αγγλικά')
    seo_keywords = models.CharField(max_length=160, default='Εστιατόριο, Λακωνία')
    seo_description = models.CharField(max_length=160, default='Μία παραδοσιακή ψαροταβέρνα...')
    seo_keywords_eng = models.CharField(max_length=160, default='Εστιατόριο, Λακωνία')
    seo_description_eng = models.CharField(max_length=160, default='Μία παραδοσιακή ψαροταβέρνα...')

    class Meta:
        verbose_name_plural = '3. Διαχείριση σελίδας Reservation'

    def __str__(self):
        return self.left_title

blog/forms.py
from django import forms
from .models import *



class PostCreate(forms.ModelForm):
    title = forms.CharField(label="Τίτλος 'Αθρου", widget=forms.TextInput(attrs={'onkeyup':"myTitle()",}))
    lead_content = forms.CharField(label='Πρώτα Σχόλια', widget=forms.Textarea(attrs={'onkeyup':"myLeadCon()",}))
    content = forms.CharField(label='Βασικό Κείμενο', widget=forms.Textarea(attrs={'onkeyup':"myCon()",}))
    #content = forms.CharField(label='Βασικό Κείμενο', widget=FroalaEditor(attrs={'onkeyup':"myCon()",}))
    #user = forms.ChoiceField(widget=forms.HiddenInput())
    #publish = forms.DateTimeField(widget=forms.DateTimeField())

    class Meta:
        model=Post
        fields = '__all__'
        exclude=['publish','user']

class PostTagForm(forms.ModelForm):

    class Meta:
        model = PostTags
        fields= '__all__'

class PostCategoryForm(forms.ModelForm):

    class Meta:
        model = PostCategory
        fields = '__all__'

contact/forms.py
from django import forms
from .models import Contact, ContactInfo


class ContactFormGr(forms.ModelForm):
    #date = forms.DateTimeField(widget=forms.HiddenInput())
    class Meta:
        model = Contact
        fields = '__all__'
        exclude =['date', 'is_readed']



class ContactFormEng(forms.ModelForm):
    #date = forms.DateTimeField(widget=forms.HiddenInput())
    class Meta:
        model = Contact
        fields = '__all__'
        exclude =['date', 'is_readed']


class ContactInfoForm(forms.ModelForm):

    class Meta:
        model = ContactInfo
        fields ='__all__'
        exclude = ['date']

blog/views.py
from django.shortcuts import render, render_to_response,get_list_or_404, HttpResponseRedirect
from .models import *
from django.template.context_processors import csrf
from django.contrib.contenttypes.models import ContentType
# Create your views here.

'''

def blog_homepage(request):
    welcome_page = WelcomePage.objects.get(id=1)
    categories = CategorySite.objects.all().filter(category__isnull=True).order_by('id')
    posts = Post.objects.all() or get_list_or_404
    post_category = PostCategory.objects.all()
    return render_to_response('obaju/blog.html',{'posts':posts,
                                                 'categories':categories,
                                                 'welcome_page':welcome_page,
                                                 'post_cat':post_category
                                                 })
def blog_category(request,slug):
    welcome_page = WelcomePage.objects.get(id=1)
    categories = CategorySite.objects.all().filter(category__isnull=True).order_by('id')
    choosed_category = PostCategory.objects.get(slug=slug)
    posts = Post.objects.filter(category = choosed_category) or get_list_or_404
    post_category = PostCategory.objects.all()
    return render_to_response('obaju/blog.html',{'posts':posts,
                                                 'categories':categories,
                                                 'welcome_page':welcome_page,
                                                 'post_cat':post_category,
                                                 'choosed_category':choosed_category,
                                                 })

def blog_details(request,slug):
    welcome_page = WelcomePage.objects.get(id=1)
    categories = CategorySite.objects.all().filter(category__isnull=True).order_by('id')
    post_category = PostCategory.objects.all()
    post= Post.objects.get(slug=slug)
    content_type = post.get_content_type
    object_id = post.id
    comments = Comment.my_query.filter_by_instance(instance=post)

    if request.POST:
        form_comment = CommentForm(request.POST)
        if form_comment.is_valid():
            get_data = form_comment.cleaned_data.get('content')
            new_comment = Comment.objects.create(content_type=content_type,
                                                object_id =object_id,
                                                user=request.user,
                                                comment_type=CommentType.objects.get(id = 1),
                                                content = get_data,
                                                )
            new_comment.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form_comment = CommentForm()

    context={
        'post':post,
        'blog_detail':True,
        'categories':categories,
        'welcome_page':welcome_page,
        'post_cat':post_category,
        'comments':comments,
        'form_comment':form_comment,

    }
    context.update(csrf(request))

    return render(request,'obaju/post.html',context)



def create_post(request):
    posts  = Post.objects.all() or get_list_or_404
    if request.POST:
        form = PostCreate(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/blog/')
    else:
        form = PostCreate()
    context={
            'posts':posts,
            'create':True,
            'form':form,

            }
    return render(request,'blog/blog_homepage.html',context)





def edit_post(request,slug):
    posts  = Post.objects.all() or get_list_or_404
    post= Post.objects.get(slug=slug)
    if request.POST:
        form = PostCreate(request.POST,instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/blog/')
    else:
        form = PostCreate(instance=post)
    context ={'posts':posts,
            'create':True,
            'form':form,}
    context.update(csrf(request))
    return render(request, 'blog/blog_homepage.html',context)
'''

contact/views.py
from django.shortcuts import render

# Create your views here.

homepage/templates/english/reservation-en.html
{% extends 'english/index-en.html' %}
{% load staticfiles %}
{% block seo %}
    <title>{{ index_page.title_eng }} | Reservation</title>
    <meta name="description" content="{{ res_info.description_eng }}">
    <meta name="keywords" content="{{ res_info.keywords_eng }}">
{% endblock %}

{% block menu %}
     <ul class="nav-links nav navbar-nav">
         <li><a href="{% url 'homepage_eng' %}" class="main-menu"><span class="text">Homepage</span></a></li>
         <li><a href="{% url 'menu_eng' %}" class="main-menu"><span class="text">menu</span></a></li>
         <!--<li><a href="{% url 'about_eng' %}" class="main-menu"><span class="text">About</span></a></li> -->
         <li class="active"><a href="{% url 'reservation_eng' %}" class="main-menu"><span class="text">Reservation</span></a></li>
         <li><a href="{% url 'blog_eng' %}" class="main-menu"><span class="text">blog</span></a></li>
         <li><a href="{% url 'contact_eng' %}" class="main-menu"><span class="text">contact</span></a></li>
     </ul>
{% endblock %}
{% block content %}
    <div id="wrapper-content">
                    <!-- MAIN CONTENT-->
                    <div class="main-contents">
                        <section class="morepage-banner-wrapper reservation">
                            <div class="container">
                                <div class="morepage-banner">
                                    <h2 class="title">reservation</h2>
                                    <ol class="breadcrumb">
                                        <li><a href="{% url 'homepage_eng' %}" class="link">Home</a></li>
                                        <li class="active"><a href="{% url 'reservation' %}" class="link">reservation</a></li>
                                    </ol>
                                </div>
                            </div>
                        </section>
                        <section class="book-table style-4 padding-top-100 padding-bottom-100">
                            <div class="container">
                                {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                        <li{% if message.tags %} class="alert alert-success"{% endif %}>
                                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                                            {{ message }}
                                        </li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                <div class="main-title-2">
                                    <div class="icons">//</div>
                                    <h2 class="title">Make online Reservation</h2>
                                    <h5 class="subtitle">Diamantis</h5></div>
                                <div class="main-content">
                                    <form method="post">{% csrf_token %}
                                        <div class="row form-group">
                                            <div class="col-sm-6 col-xs-6">
                                                <div class="input-group"><input name="name" type="text" placeholder="Name" onfocus="this.placeholder = ''" class="form-control" required>
                                                    <div class="input-group-addon"><i class="fa fa-user"></i></div>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 col-xs-6">
                                                <div class="input-group"><input name="phone" type="number" placeholder="Phone" onfocus="this.placeholder = ''" class="form-control" required>
                                                    <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 col-xs-6">
                                                <div class="input-group"><input name="email" type="email" placeholder="Email (Optional)" onfocus="this.placeholder = ''" class="form-control">
                                                    <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 col-xs-6">
                                                <div class="input-group"><input name="people" type="number" placeholder="Number of people" onfocus="this.placeholder = ''" class="form-control" required>
                                                    <div class="input-group-addon"><i class="fa fa-users"></i></div>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 col-xs-6">
                                                <div class="input-group"><input name="resever_date" type="date" placeholder="Date" class="form-control" required>
                                                    <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 col-xs-6">
                                                <div class="input-group"><input name="time" type="time" placeholder="Time" onfocus="this.placeholder = ''" class="form-control" required>
                                                    <div class="input-group-addon"><i class="fa fa-clock-o"> </i></div>
                                                </div>
                                            </div>
                                            <div class="col-sm-12 col-xs-12">
                                                <div class="input-group"><input type="text" id='id_message' name="message" placeholder="Message(Optional)" onfocus="this.placeholder = ''" class="form-control">
                                                    <div class="input-group-addon"><i class="fa fa-message"> </i></div>
                                                </div>
                                            </div>
                                        </div><button type="submit" class="btn">Resever Now</button>
                                    </form>

                                    <div class="more-infomation margin-top-70">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <h3 class="title-info">{{ res_info.left_title_eng }}</h3>
                                                {{ res_info.left_text_eng|safe }}
                                            </div>
                                            <div class="col-sm-6">
                                                <h3 class="title-info">{{ res_info.right_title_eng }}</h3>
                                                {{ res_info.right_text_eng|safe }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="bg-images-pc"><img src="{% static 'images/diamantis/item-clam.png' %}" alt="" class="img-responsive"></div>
                                </div>
                            </div>
                        </section>
                        <div class="banner taste-of-fresh-wrapper padding-top-100 padding-bottom-100">
                            <div class="container">
                                <div class="taste-of-fresh">
                                    <div class="title">
                                        <div class="name-3">{{ res_info.banner_title_eng }}</div>
                                    </div>
                                    {{ res_info.banner_text_eng|safe }}<br>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
{% endblock %}